export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'
export const PRODUCT_LIST_RESET = 'PRODUCT_LIST_RESET'

export const PRODUCT_DELETE_ADMIN_REQUEST = 'PRODUCT_DELETE_ADMIN_REQUEST'
export const PRODUCT_DELETE_ADMIN_SUCCESS = 'PRODUCT_DELETE_ADMIN_SUCCESS'
export const PRODUCT_DELETE_ADMIN_FAIL = 'PRODUCT_DELETE_ADMIN_FAIL'

export const PRODUCT_CREATE_ADMIN_REQUEST = 'PRODUCT_CREATE_ADMIN_REQUEST'
export const PRODUCT_CREATE_ADMIN_SUCCESS = 'PRODUCT_CREATE_ADMIN_SUCCESS'
export const PRODUCT_CREATE_ADMIN_FAIL = 'PRODUCT_CREATE_ADMIN_FAIL'
export const PRODUCT_CREATE_ADMIN_RESET = 'PRODUCT_CREATE_ADMIN_RESET'

export const PRODUCT_UPDATE_ADMIN_SUCCESS = 'PRODUCT_UPDATE_ADMIN_SUCCESS'
export const PRODUCT_UPDATE_ADMIN_REQUEST = 'PRODUCT_UPDATE_ADMIN_REQUEST'
export const PRODUCT_UPDATE_ADMIN_FAIL = 'PRODUCT_UPDATE_ADMIN_FAIL'
export const PRODUCT_UPDATE_ADMIN_RESET = 'PRODUCT_UPDATE_ADMIN_RESET'

export const PRODUCT_CREATE_REVIEW_SUCCESS = 'PRODUCT_UPDATE_REVIEW_SUCCESS'
export const PRODUCT_CREATE_REVIEW_REQUEST = 'PRODUCT_UPDATE_REVIEW_REQUEST'
export const PRODUCT_CREATE_REVIEW_FAIL = 'PRODUCT_UPDATE_REVIEW_FAIL'
export const PRODUCT_CREATE_REVIEW_RESET = 'PRODUCT_UPDATE_REVIEW_RESET'

export const PRODUCT_TOP_SUCCESS = 'PRODUCT_TOP_SUCCESS'
export const PRODUCT_TOP_REQUEST = 'PRODUCT_TOP_REQUEST'
export const PRODUCT_TOP_FAIL = 'PRODUCT_TOP_FAIL'

export const PRODUCT_UPDATE_REVIEW_SUCCESS = 'PRODUCT_UPDATE_REVIEW_SUCCESS'
export const PRODUCT_UPDATE_REVIEW_REQUEST = 'PRODUCT_UPDATE_REVIEW_REQUEST'
export const PRODUCT_UPDATE_REVIEW_FAIL = 'PRODUCT_UPDATE_REVIEW_FAIL'
export const PRODUCT_UPDATE_REVIEW_RESET = 'PRODUCT_UPDATE_REVIEW_RESET'